kind: List
apiVersion: v1
items:
- apiVersion: policy/v1beta1
  kind: PodDisruptionBudget
  metadata:
    name: pdb-tester
    namespace: pdb-test
  spec:
    maxUnavailable: 33%
    selector:
      matchLabels:
        app: pdb-tester
